version: '3.8'
services:
  stock-app:
    build: .
    image: ai-stock-app:latest
    container_name: stock-dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # 将本地代码映射到容器，修改代码后网页会自动刷新
    restart: always